export const allProductsData = [
    {
      id: 1,
      tag: "Just In",
      title: "Nike Air Force 1 Mid '07",
      category: "Men's shoes",
      color: "1 Color",
      price: "MRP : ₹ 10 795.00",
      imageUrl: "/images/Rectangle1.png",
    },
    {
      id: 2,
      tag: "Just In",
      title: "Nike Court Vision Low Next Nature",
      category: "Men's shoes",
      color: "1 Color",
      price: "MRP : ₹ 4 995.00",
      imageUrl: "/images/Rectangle 2.png",
    },
    {
      id: 3,
      tag: "Just In",
      title: "Nike Air Force 1 PLT.AF.ORM",
      category: "Men's shoes",
      color: "1 Color",
      price: "MRP : ₹ 8 695.00",
      imageUrl: "/images/Rectangle 3.png",
    },
    {
      id: 4,
      tag: "Just In",
      title: "Nike Air Force 1 React",
      category: "Men's shoes",
      color: "1 Color",
      price: "MRP : ₹ 13 295.00",
      imageUrl: "/images/Rectangle 4.png",
    },
    {
      id: 5,
      tag: "Promo Exclusion",
      title: "Air Jordan 1 Elevate Low",
      category: "Women's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 11 895.00",
      imageUrl: "/images/Rectangle 5.png",
    },
    {
      id: 6,
      tag: "Just In",
      title: "Nike Standard Issue",
      category: "Women's Basketball Jersey",
      color: "1 Colour",
      price: "MRP : ₹ 2 895.00",
      imageUrl: "/images/Rectangle 6.png",
    },
    {
      id: 7,
      tag: "Promo Exclusion",
      title: "Nike Dunk Low Retro SE",
      category: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 9 695.00",
      imageUrl: "/images/Rectangle 7.png",
    },
    {
      id: 8,
      tag: "Sustainable Materials",
      title: "Nike Dri-FIT UV Hyverse",
      category: "Men's Short Sleeve Graphic Fitness Top",
      color: "1 Colour",
      price: "MRP : ₹ 2 495.00",
      imageUrl: "/images/Rectangle 8.png",
    },
    {
      id: 9,
      tag: "Just In",
      title: "Nike Court Vision Low",
      category: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 5 695.00",
      imageUrl: "/images/Rectangle 9.png",
    },
    {
      id: 10,
      tag: "Just In",
      title: "Nike Dri-FIT Ready",
      category: "Men's Short Sleeve Fitness Top",
      color: "3 Colours",
      price: "MRP : ₹ 2 495.00",
      imageUrl: "/images/Rectangle 10.png",
    },
    {
      id: 11,
      tag: "Just In",
      title: "Nike One Leak Protection: Period",
      cateory: "Women's Mid-Rise 18cm (approx.) Biker Shorts",
      color: "2 Colours",
      price: "MRP : ₹ 3 395.00",
      imageUrl: "/images/Rectangle 11.png",
    },
    {
      id: 12,
      tag: "Just In",
      title: "Nike Air Force 1 LV8 3",
      category: "Older Kids' Shoe",
      color: "1 Colour",
      price: "MRP : ₹ 7 495.00",
      imageUrl: "/images/Rectangle 12.png",
    },
    {
      id: 13,
      tag: "Just In",
      title: "Nike Blazer Low Platform",
      category: "Women's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 195.00",
      imageUrl: "/images/Rectangle 13.png",
    },
    {
      id: 14,
      tag: "Just In",
      title: "Nike Air Force 1 '07",
      category: "Women's Shoe",
      color: "2 Colours",
      price: "MRP : ₹ 8 195.00",
      imageUrl: "/images/Rectangle 14.png",
    },
    {
      id: 15,
      tag: "Just In",
      title: "Nike Pro Dri-FIT",
      category: "Men's Tight-Fit Sleeveless Top",
      color: "1 Colour",
      price: "MRP : ₹ 1 495.00",
      imageUrl: "/images/Rectangle 15.png",
    },
    {
      id: 16,
      tag: "Just In",
      title: "Nike Dunk Low Retro",
      category: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 695.00",
      imageUrl: "/images/Rectangle 16.png",
    },
    {
      id: 17,
      tag: "Just In",
      title: "Nike Air Max SC",
      category: "Women's Shoes",
      color: "2 Colours",
      price: "MRP : ₹ 5 995.00",
      imageUrl: "/images/Rectangle 17.png",
    },
    {
      id: 18,
      tag: "Just In",
      title: "Nike Dri-FIT UV Miler",
      category: "Men's Short Sleeve Running Top",
      color: "1 Colour",
      price: "MRP : ₹ 1 695.00",
      imageUrl: "/images/Rectangle 18.png",
    },
    {
      id: 19,
      tag: "Just In",
      title: "Nike Air Max SYSTM",
      category: "Older Kids' Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 6 495.00",
      imageUrl: "/images/Rectangle 19.png",
    },
    {
      id: 20,
      tag: "Just In",
      title: "Nike Alate All U",
      category: "Women's Light Support Lightly Lined UNeck Printed Sports Bra",
      color: "1 Colour",
      price: "MRP : ₹ 2 195.00",
      imageUrl: "/images/Rectangle 20.png",
    },
    {
      id: 21,
      tag: "Just In",
      title: "Nike Court Legacy Lift",
      category: "Women's Shoes",
      color: "2 Colours",
      price: "MRP : ₹ 7 495.00",
      imageUrl: "/images/Rectangle 21.png",
    },
    {
      id: 22,
      tag: "Just In",
      title: "Nike Swoosh",
      category: "Women's Medium support Padded Sports Bra Tank",
      color: "2 Colours",
      price: "MRP : ₹ 3 095.00",
      imageUrl: "/images/Rectangle 22.png",
    },
    {
      id: 23,
      tag: "Just In",
      title: "Nike SB Zoom Janoski OG+",
      category: "Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 595.00",
      imageUrl: "/images/Rectangle 23.png",
    },
    {
      id: 24,
      tag: "Just In",
      title: "Nike Dri-FIT Run Division Rise 365",
      category: "Men's Running Tank",
      color: "2 Colours",
      price: "MRP : ₹ 3 495.00",
      imageUrl: "/images/Rectangle 24.png",
    },
    {
      id: 25,
      tag: "Just In",
      title: "Nike Dri-FIT Challenger",
      category: "Men's 18cm (approx.) 2-in 1 Versatile Shorts",
      color: "1 Colour",
      price: "MRP : ₹ 2 495.00",
      imageUrl: "/images/Rectangle 25.png",
    },
  ];